# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
print(np.show_config())

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/prade/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/prade/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/prade/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/prade/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/prade/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/prade/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/prade/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/prade/anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
zeros=np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
array = np.random.rand(1,10)
#float value memory size
print(array.size*array.itemsize)

80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
(np.arange(0,10) == 4)*1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
array = np.random.randint(1,10,10)
print(array)
print(array[::-1])

[6 9 4 5 1 7 1 2 3 6]
[6 3 2 1 7 1 5 4 9 6]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
threed = np.arange(0,9).reshape(3,3)
print(threed)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
print(np.array([1,2,0,0,4,0]).nonzero())

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
threed = np.random.rand(3,3,3)
print(threed)


[[[0.73858816 0.49565739 0.38330074]
  [0.9731795  0.1019583  0.31593498]
  [0.97663493 0.611469   0.92261325]]

 [[0.16017393 0.8889708  0.37351551]
  [0.94801471 0.60319079 0.09682448]
  [0.44461956 0.42427656 0.87402664]]

 [[0.68113251 0.6041088  0.74559258]
  [0.94323449 0.50406082 0.83385026]
  [0.99068703 0.54555331 0.02849759]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
samplearray=np.random.randint(1,100,100).reshape(10,10)
print(samplearray)
print(f"Minimum - {samplearray.min()}, Maximim - {samplearray.max()}")


[[ 6 97 29 91 81 93 27 10 78 42]
 [97 54 86 24 49 17 59  8 94 63]
 [80 40 43 66 47 64 43 92 19 27]
 [84 64 83 17 19 10 58  4 26 26]
 [61 62 31 48 62 34 26 80 59 51]
 [28  1  2 39 76 12 65  9 51 79]
 [72 31 67  4 78 24 79 53  7 23]
 [77 98 10 22 56 11 75  7 12 13]
 [58 70 68 97 56 47  6 70 22 48]
 [19 40  8 57 67 23 96 71 34 47]]
Minimum - 1, Maximim - 98


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [14]:
samplearray=np.random.randint(1,100,30)
samplearray.mean()

52.06666666666667

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [15]:
border=np.ones((5,5),int)

border[1:-1,1:-1]=0

border


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
arr = np.random.randint(1,26,16).reshape(4,4)
print(arr)
np.pad(arr,1)

[[11  1 24 17]
 [ 7  9 11 20]
 [24  8 24 18]
 [22  8 21 12]]


array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  1, 24, 17,  0],
       [ 0,  7,  9, 11, 20,  0],
       [ 0, 24,  8, 24, 18,  0],
       [ 0, 22,  8, 21, 12,  0],
       [ 0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [18]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [19]:
check=np.ones((8,8),dtype=int)
check[0:-1:2,0:-1:2]=0
check[1:8:2,1:8:2]=0

print(check)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [20]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [21]:
temp=np.array([[1,0],[0,1]])

print(np.tile(temp,(4,4)))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [22]:
normalize=np.random.rand(5,5)

mini=normalize.min()
avg=normalize.max()-mini
print((normalize-mini)/(avg))

[[0.26015184 0.4184164  0.51610187 0.63339159 0.13482262]
 [0.1255045  1.         0.71098985 0.49819287 0.        ]
 [0.57588477 0.24251522 0.934919   0.81613996 0.23032987]
 [0.13126642 0.03083878 0.39360013 0.91785088 0.4403896 ]
 [0.59027474 0.2283336  0.92297667 0.92087851 0.82243358]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [23]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [24]:
x=np.random.randint(1,20,15).reshape(5,3)
y=np.random.randint(1,20,6).reshape(3,2)
print(np.dot(x,y))
print(x@y)

[[352 432]
 [139 284]
 [333 409]
 [239 416]
 [209 419]]
[[352 432]
 [139 284]
 [333 409]
 [239 416]
 [209 419]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [25]:
array1 =np.random.randint(1, 12,10) 
print(array1 , end="\n\n")
print(array1[(3 > array1) | (array1  > 8)])


[ 5  9  8  5  8  9  2  6 11  9]

[ 9  9  2 11  9]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(9,10)

9 10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
z=np.arange(1,5)
z**z
2 << z >> 2
z <-z
1j*z
z/1/1


array([1., 2., 3., 4.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.nan,0,np.array([np.nan]).astype(int).astype(float))

nan 0 [-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [29]:
flat=np.random.uniform(1,100,10)
print(np.copysign(np.ceil(np.abs(flat)),flat))


[ 51. 100.  24.   4.  96.  77.  40.  17.   8.  35.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [30]:
x= np.arange(1,10)
y=np.arange(8,15)

np.intersect1d(x,y)

array([8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [31]:
default=np.seterr(all="ignore")
np.ones(1)/0
np.seterr(**default)
np.ones(1)/0


C:\Users\prade\AppData\Local\Temp/ipykernel_12668/2613193036.py:4: RuntimeWarning: divide by zero encountered in true_divide
  np.ones(1)/0


array([inf])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.emath.sqrt(-1) == np.sqrt(-1)


C:\Users\prade\AppData\Local\Temp/ipykernel_12668/3492825685.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.emath.sqrt(-1) == np.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [33]:
print(np.datetime64('today') - np.timedelta64(1),np.datetime64('today'),np.datetime64('today') +np.timedelta64(1),sep=",")

2022-04-07,2022-04-08,2022-04-09


## 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [34]:
np.arange("2016-07","2016-08",dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [35]:
a=np.arange(1,11)
b=np.arange(11,21)
np.add(a,b,out=b)
np.divide(a,2)
np.negative(a,out=a)
np.multiply(a,b)

array([ -12,  -28,  -48,  -72, -100, -132, -168, -208, -252, -300])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [36]:
rand=np.random.random(9)
np.floor(rand)
np.ceil(rand)
rand.astype(int)
np.trunc(rand)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [37]:
np.arange(5)+np.ones((5,5))
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [38]:

def generator():
    for j in np.random.randint(0,10,10):
        yield j

np.fromiter(generator(),dtype=int)

array([3, 5, 7, 3, 9, 6, 4, 4, 9, 8])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [39]:
np.linspace(0.1,0.9,10)

array([0.1       , 0.18888889, 0.27777778, 0.36666667, 0.45555556,
       0.54444444, 0.63333333, 0.72222222, 0.81111111, 0.9       ])

# 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [40]:
k= np.random.randint(1,11,10)
print(k)
print(np.sort(k))

[8 8 2 8 1 6 5 9 3 8]
[1 2 3 5 6 8 8 8 8 9]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [41]:
np.add.reduce(np.random.randint(10,20,10))

146

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [42]:
n=np.random.randint(10,20,10)
m=np.random.randint(10,20,10)

np.allclose(n,m)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [43]:
mut=np.array([1,2,3,4,5])
mut.flags.writeable=False

mut[1]=0

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
Z = np.random.random((10,2))
print(Z)
X,Y = Z[:,0], Z[:,1]
print(X,Y)
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
maxi=np.random.randint(1,100,10)
print(maxi)
maxi[maxi.argmax()] =0
print(maxi)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions()
print(np.ones((20,20)))

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
linear = np.arange(100)
rand= np.random.uniform(0,100)
index = (np.abs(rand-linear)).argmin()
print(Z[index])

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
np.seterr(all="ignore")
pos = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])

print(pos)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
flo = (np.random.rand(10)*100).astype(np.float32)
inte = Z.view(np.int32)

flo,inte.T

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s,delimiter=",", dtype=np.int)
print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)
for index, value in np.ndenumerate(Z):
    print(index, value)
print("****************************")
for index in np.ndindex(Z.shape):
    print(index, Z[index])

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

import pandas as pd-+-
p=pd.DataFrame(G)
p.plot()

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n=np.ones((5,5),int)

np.put(n, np.random.choice(range(25),2 ),0)
n

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
mean = np.random.randint(1,20,(5,5))

mean-mean.mean(axis=1,keepdims=True)

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x=np.random.randint(1,20,(5,5))

print(x)


print(x[:,1])

x[:,1].argsort()

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
x=np.random.randint(1,20,(5,5))
print(x)
~x.any(axis=0,).any()

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
import pandas as pd

uni=np.random.uniform(1,20,(4,5))
print(uni)
uni.flat[np.abs(uni-0).argmin()]

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
it.operands[2]

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
x=np.ones(10,dtype=int)
y=np.random.randint(0,10,20)

x+=np.bincount(y,minlength=10)
print(x)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [53]:
X = [1,1,1,1,1]
I = [0,1,2,3,1]
F = np.bincount(I,X)
print(F)

[1. 2. 1. 1.]


In [58]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [66]:
fd = np.random.randint(0,5,(2,3,2,3))

fd.sum(axis=(-2,-1))


array([[18, 16, 12],
       [16, 12,  9]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [68]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
print(D_sums)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[8.54238837 6.14345282 3.01876269 6.86085343 3.19536436 4.27879274
 6.24149686 6.53294    2.97007746 4.72246602]
[0.44959939 0.68260587 0.43125181 0.57173779 0.45648062 0.61125611
 0.69349965 0.54441167 0.33000861 0.52471845]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [71]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(A@B)

array([1.07497106, 1.40699104, 0.51566031, 1.62345378, 0.7145823 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [77]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [87]:
td=np.random.randint(1,10,(5,5,3))
twod=np.random.randint(1,10,(5,5))
print(twod[:,:,None]*td)


[[[ 9 45 72]
  [ 3  6  6]
  [28 12 12]
  [40 20 35]
  [16  4  4]]

 [[35 25 30]
  [ 9  1  5]
  [20 40 10]
  [10  2 18]
  [72 72 45]]

 [[ 3  8  3]
  [30 54 48]
  [28  8 20]
  [ 8 16 12]
  [24 27 27]]

 [[25 35 30]
  [36 20 36]
  [ 3 15  9]
  [ 6 27 24]
  [42  6 30]]

 [[56 56 63]
  [15 18  3]
  [ 6  5  7]
  [24 18 27]
  [ 6  4  8]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [94]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [102]:

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 12) ( 0, 65) ( 1, 59) ( 1, 70) ( 3,  9) ( 3, 24) ( 9, 24) (12, 65)
 (14, 21) (14, 57) (21, 57) (23, 71) (23, 88) (28, 61) (28, 96) (30, 64)
 (30, 75) (33, 34) (33, 51) (34, 51) (40, 84) (40, 89) (59, 70) (61, 96)
 (64, 75) (70, 76) (71, 88) (76, 76) (84, 89)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [109]:
bc=np.bincount([1,1,2,3,4,4,6])

print(bc)
np.repeat(np.arange(len(bc)),bc)

[0 2 1 1 2 0 1]


array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [111]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    print(ret)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[  0.   1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91.
 105. 120. 136. 153. 171. 190.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [117]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)

print(sliding_window_view(Z, window_shape=3).mean(axis=-1))
Z

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [124]:
Z = np.random.randint(0,3,100)
np.logical_not(Z, out=Z)

np.negative(Z,out=Z)

array([ 0, -1, -1, -1,  0,  0,  0,  0,  0,  0,  0, -1,  0, -1, -1, -1, -1,
        0, -1,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0, -1, -1,  0,  0,  0,
       -1,  0,  0, -1,  0,  0,  0,  0, -1,  0,  0,  0,  0, -1,  0, -1,  0,
        0,  0,  0,  0, -1,  0, -1, -1,  0, -1, -1, -1, -1,  0,  0,  0,  0,
        0, -1,  0,  0,  0,  0,  0, -1,  0, -1, -1, -1,  0,  0, -1,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0, -1, -1,  0, -1,  0,  0])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [125]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[10.40113184  9.63589453  9.80978261  5.64968219  0.46364609  1.63102898
  3.39856198  9.39784585  3.86249086  3.39455016]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [126]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 6.51139953  4.53736697  5.53455457  2.77086973  4.34398861  2.85867248
   8.76486125  1.66935182  1.50772766  3.31290169]
 [ 5.28881615  6.81641029  7.46076611  5.32736199  1.95865629  3.3794117
  11.20030096  4.3195805   0.73127938  4.48616347]
 [ 4.97462664 15.4440217  15.62550671 14.0600827   6.75100993  1.34329168
  19.93393597 12.94746006  1.94305937 11.15841662]
 [13.03774587  9.14508755 11.24942939  5.96803955  0.18948103  4.44712506
  12.67502248  4.09722235  8.59622083 10.33775   ]
 [10.05953421 11.86314659 13.23913967  9.35005106  2.76820953  2.41399398
  15.75086623  7.75300613  6.20749549 10.95099276]
 [ 5.94967818  4.32344357  5.21688462  2.67912007  4.51766071  3.4381935
   8.61247193  1.64088711  0.92967876  2.8529777 ]
 [ 5.6217325   0.47938381  1.48438615  1.10924723  8.36353647  4.78006975
   4.77389189  2.05090632  0.06049469  0.36182596]
 [ 3.71650575  8.75537109  8.99187814  7.61896716  0.11024563  4.316786
  13.33227554  6.74764021  0.44137034  5.20917754]
 [ 6

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [127]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 5 9 0 9 4 4 9 5 8]
 [4 7 9 4 8 1 2 1 3 5]
 [3 7 4 5 2 3 2 3 7 5]
 [2 0 8 2 4 6 6 5 7 5]
 [5 5 0 3 5 6 3 8 9 6]
 [4 5 7 4 8 1 7 0 6 4]
 [0 3 3 0 3 2 9 6 9 3]
 [7 6 3 8 1 7 9 4 1 9]
 [0 7 3 7 6 4 6 1 1 9]
 [7 9 4 7 9 2 7 8 5 2]]
[[0 0 0 0 0]
 [0 4 5 9 0]
 [0 4 7 9 4]
 [0 3 7 4 5]
 [0 2 0 8 2]]


C:\Users\prade\AppData\Local\Temp/ipykernel_12668/1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [132]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [133]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)


10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [134]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [135]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)



[[[[0 1 3]
   [3 2 0]
   [1 3 3]]

  [[1 3 3]
   [2 0 2]
   [3 3 4]]

  [[3 3 1]
   [0 2 0]
   [3 4 3]]

  [[3 1 2]
   [2 0 0]
   [4 3 3]]

  [[1 2 2]
   [0 0 1]
   [3 3 3]]

  [[2 2 0]
   [0 1 0]
   [3 3 0]]

  [[2 0 2]
   [1 0 3]
   [3 0 2]]

  [[0 2 0]
   [0 3 1]
   [0 2 4]]]


 [[[3 2 0]
   [1 3 3]
   [4 4 1]]

  [[2 0 2]
   [3 3 4]
   [4 1 4]]

  [[0 2 0]
   [3 4 3]
   [1 4 0]]

  [[2 0 0]
   [4 3 3]
   [4 0 4]]

  [[0 0 1]
   [3 3 3]
   [0 4 4]]

  [[0 1 0]
   [3 3 0]
   [4 4 3]]

  [[1 0 3]
   [3 0 2]
   [4 3 2]]

  [[0 3 1]
   [0 2 4]
   [3 2 0]]]


 [[[1 3 3]
   [4 4 1]
   [4 4 1]]

  [[3 3 4]
   [4 1 4]
   [4 1 3]]

  [[3 4 3]
   [1 4 0]
   [1 3 2]]

  [[4 3 3]
   [4 0 4]
   [3 2 2]]

  [[3 3 3]
   [0 4 4]
   [2 2 0]]

  [[3 3 0]
   [4 4 3]
   [2 0 2]]

  [[3 0 2]
   [4 3 2]
   [0 2 0]]

  [[0 2 4]
   [3 2 0]
   [2 0 2]]]


 [[[4 4 1]
   [4 4 1]
   [0 0 0]]

  [[4 1 4]
   [4 1 3]
   [0 0 2]]

  [[1 4 0]
   [1 3 2]
   [0 2 1]]

  [[4 0 4]
   [3 2 2]
   [2 1 3]]

  [[0 4 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [137]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


[[ 1  8  4  8 11]
 [ 8  9  0 10  4]
 [ 4  0  7 42 16]
 [ 8 10 42  5 11]
 [11  4 16 11  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [138]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [139]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [140]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [143]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 10

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]
[9999 9998 9995 9992 9997 9991 9996 9993 9994 9990]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [144]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [145]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [146]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.32 s ± 172 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
159 ms ± 3.92 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
124 ms ± 997 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [152]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [153]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 3 3]
 [0 0 4]
 [4 4 0]
 [4 0 4]
 [1 4 4]
 [3 3 4]
 [1 1 4]
 [4 1 0]
 [2 2 4]
 [0 3 1]]
[[1 3 3]
 [0 0 4]
 [4 4 0]
 [4 0 4]
 [1 4 4]
 [3 3 4]
 [1 1 4]
 [4 1 0]
 [2 2 4]
 [0 3 1]]
[[1 3 3]
 [0 0 4]
 [4 4 0]
 [4 0 4]
 [1 4 4]
 [3 3 4]
 [1 1 4]
 [4 1 0]
 [2 2 4]
 [0 3 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [156]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 1])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [157]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [158]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.23955044, 0.33964078, 0.38512487, 0.44350759, 0.40569618,
        0.01984704, 0.25063142, 0.37874081, 0.192164  , 0.3491354 ],
       [0.44954887, 0.63738195, 0.72273902, 0.83230211, 0.76134386,
        0.03724566, 0.47034382, 0.71075846, 0.36062178, 0.6551999 ],
       [0.22059416, 0.31276407, 0.35464889, 0.40841162, 0.37359233,
        0.01827649, 0.23079827, 0.34877001, 0.17695753, 0.32150736],
       [0.33926991, 0.4810256 , 0.5454437 , 0.62812984, 0.57457838,
        0.02810891, 0.35496364, 0.5364021 , 0.27215755, 0.49447262],
       [0.35389912, 0.50176727, 0.56896306, 0.65521459, 0.59935401,
        0.02932096, 0.37026956, 0.55953158, 0.28389289, 0.51579412],
       [0.45236829, 0.6413794 , 0.7272718 , 0.83752203, 0.76611875,
        0.03747925, 0.47329366, 0.7152161 , 0.36288348, 0.65930909],
       [0.3773609 , 0.53503199, 0.60668253, 0.69865212, 0.63908826,
        0.0312648 , 0.39481663, 0.5966258 , 0.30271361, 0.54998875],
       [0.30493976, 0.43235144, 0.4902511

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [160]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [161]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [162]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.29248702  0.10503942]
